update-cicd

diff --git a/.github/workflows/dash.yml b/.github/workflows/dash.yml
--- a/.github/workflows/dash.yml
+++ b/.github/workflows/dash.yml
@@ -1,85 +1,101 @@
 name: dash
 
 on:
-  workflow_call:
-    inputs:
-      scala-version:
-        required: false
-        type: string
-        default: "2.12"
+  pull_request:
+  workflow_dispatch:
+  schedule:
+    - cron: '20 21 * * 0'
 
 permissions:  # added using https://github.com/step-security/secure-repo
   contents: read
 
 env:
-  MAVEN_CLI_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dlicense.skip=true --batch-mode
+  JAVA_VERSION: 17
+  MAVEN_CLI_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false --batch-mode -Dlicense.skip=true
+  MAVEN_COMPILE_NO_OP_ARGS: clean install -Dmaven.test.skip -Dmaven.assembly.skip=true -Dmaven.source.skip -Pskip-spark-runtimes -Dmaven.main.skip
+  MAVEN_DASH_ARGS: org.eclipse.dash:license-tool-plugin:license-check -Ddash.fail=true -Ddash.projectId=locationtech.geomesa -DexcludeGroupIds=org.locationtech.geomesa
 
 jobs:
-  dependency-check:
+  license-check:
+    name: license-check
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
+      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
+      - uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
         with:
-          fetch-depth: 2 # needed for checking for pom changes
-      - name: Check for pom.xml changes
-        id: pom_changes
+          distribution: temurin
+          java-version: "${{ env.JAVA_VERSION }}"
+      - uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
+        with:
+          key: ${{ hashFiles('**/pom.xml') }}-dash
+          path: ~/.m2/repository/
+      - name: Check for dependency changes
+        id: dependency_changes
         run: |
-          if [[ "${{ github.event_name }}" == "schedule" ]]; then
-            echo "Always running scheduled dash check"
-            pomChanged="true"
-          elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
-            echo "Always running manually triggered dash check"
-            pomChanged="true"
-          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
-            pomChanged="false"
-            # get the changed files: https://stackoverflow.com/a/74268200/7809538
-            IFS=$'\n' read -r -d '' -a changedFiles < <( git diff --name-only HEAD^1 HEAD && printf '\0' )
+          changed=""
+          if [[ "${{ github.event_name }}" == 'pull_request' ]]; then
+            echo "Checking for dependency changes"
+            # get the changed files
+            git fetch --depth=1 origin ${{ github.base_ref }}
+            IFS=$'\n' read -r -d '' -a changedFiles < <( git diff --name-only origin/${{ github.base_ref }} && printf '\0' )
             echo "Changed files:"
             for file in "${changedFiles[@]}"; do
               echo "  $file"
-              if [[ $file =~ .*pom.xml ]]; then
-                pomChanged="true"
+              if [[ -z "$changed" ]] && [[ $file =~ .*pom.xml ]]; then
+                changed="pom"
+              elif [[ "$file" == "build/dependencies.txt" ]]; then
+                echo "Detected dependency change"
+                changed="true"
               fi
             done
+            if [[ -n "$changed" ]]; then
+              echo "Detected dependency change, double-checking dependencies.txt"
+              mvn $MAVEN_COMPILE_NO_OP_ARGS $MAVEN_CLI_OPTS
+              ./build/scripts/calculate-cqs.sh
+              git diff --exit-code --quiet build/dependencies.txt || {
+                echo 'Detected dependency changes - please run `./build/scripts/calculate-cqs.sh` and commit the results'
+                git diff build/dependencies.txt
+                exit 1
+              }
+              if [[ "$changed" == "pom" ]]; then
+                echo "Dependencies are ok, skipping dash check"
+                changed="false"
+              fi
+            fi
           else
-            echo "Skipping dash check for branch (main, long-term branches, and tags)"
-            pomChanged="false"
+            # weekly or dispatch requests
+            echo "Always running dash check for scheduled jobs"
+            changed="true"
           fi
-          echo "pom_changed=$pomChanged" >> "$GITHUB_OUTPUT"
-      - uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
-        if: steps.pom_changes.outputs.pom_changed == 'true'
-        with:
-          distribution: 'temurin'
-          java-version: '11'
-      - uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
-        if: steps.pom_changes.outputs.pom_changed == 'true'
-        with:
-          key: ${{ hashFiles('**/pom.xml') }}-dash-${{ inputs.scala-version }}
-          path: ~/.m2/repository/
-      - name: Set Scala version
-        if: steps.pom_changes.outputs.pom_changed == 'true'
-        run: ./build/scripts/change-scala-version.sh ${{ inputs.scala-version }}
-      - name: Download artifacts
-        if: steps.pom_changes.outputs.pom_changed == 'true'
-        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
-        with:
-          name: classes-and-jars-${{ inputs.scala-version }}
-      - name: Install artifacts
-        if: steps.pom_changes.outputs.pom_changed == 'true'
+          echo "changed=$changed" >> "$GITHUB_OUTPUT"
+      - name: Compile
+        if: steps.dependency_changes.outputs.changed == 'true'
+        id: compile
+        continue-on-error: true
         run: |
-          tar -xf classes.tgz
-          mkdir -p ~/.m2/repository/org/locationtech/geomesa
-          mv m2-geomesa/* ~/.m2/repository/org/locationtech/geomesa/
+          set -o pipefail
+          mvn $MAVEN_COMPILE_NO_OP_ARGS $MAVEN_CLI_OPTS | tee -a build.log
+      - name: Compile (retry)
+        if: steps.compile.outcome=='failure'
+        run: |
+          set -o pipefail
+          # retry if the failure was due to transient download errors from maven central
+          if grep -q -e 'Could not transfer artifact' -e 'Failed to read artifact descriptor' build.log; then
+            RESUME_FROM="$({ grep --text 'mvn <args> -rf ' build.log || test $? = 1; } | tail -n1 | sed 's/.*-rf/-rf/')"
+            mvn $MAVEN_COMPILE_NO_OP_ARGS $MAVEN_CLI_OPTS $RESUME_FROM | tee -a build.log
+          else
+            exit 1
+          fi
       - name: License check
-        if: steps.pom_changes.outputs.pom_changed == 'true'
-        run: mvn org.eclipse.dash:license-tool-plugin:license-check $MAVEN_CLI_OPTS -Ddash.fail=true -Ddash.projectId=locationtech.geomesa -DexcludeGroupIds=org.locationtech.geomesa
+        if: steps.dependency_changes.outputs.changed == 'true'
+        run: mvn $MAVEN_DASH_ARGS $MAVEN_CLI_OPTS
       - name: Show license
         if: success() || failure()
         run: |
           if [[ -f target/dash/summary ]]; then
             cat target/dash/summary
           else
-            echo "No pom changes detected - skipping license check"
+            echo "No dependency changes detected - skipping license check"
           fi
       - name: Remove geomesa artifacts
         if: success() || failure()
